### ISSUE TITLE
Support CSS custom properties

### ISSUE THREAD

**Issue by jfayad** [Geeks-Solutions/vue-cli-plugin-sections#31]
In order to speed up the production of custom css, we should define a set of css properties that will be used to style the sections.

That way, redefining the value of one property would automatically style a set of elements.

For example, using this in the section
```css
p, h2, h3, h4 {
 color: "var(--text-color)"
}

button.simple {
 color: "var(--text-color)"
}
```

could be updated through that definition
```css
  :root{
    --text-color: white;
  }
```

We first need to identify the properties we can use and then document them so they can be redefined in a custom css
